### ISSUE TITLE
Auto-authentication for new users

### ISSUE THREAD

**Issue by joshjung** [JohnnyEstilles/keystone-social-login#4]
First off let me say you write beautiful code. Super clean and neat. I love it.

I'm attempting to integrate keystone-social-login with my blog so that users can post comments using Google/Facebook authentication.

However, it appears that keystone-social-login is setup so that I would have to manually enter each person's credentials into their account in KeystoneJS.

Is there a way we could authenticate random web users but create a 'minimal' user (e.g. no access to keystone admin area) just so that they can post comments?

**Comment by estilles** [comment]
@joshjung. I'm sorry for the late reply. I was MIA during the holidays and I'm just getting back to my normal routine.

KSL already has an option for auto-creating users. Check out the [Configuration Options](https://github.com/JohnnyEstilles/keystone-social-login#configuration-options) and you will see an options called `auto create user`. It defaults to `false`, but when we to `true` it automatically creates users who successfully log in with their social media account, but do not have a Keystone user account.

If you have any other questions please let me know.

**Comment by estilles** [comment]
@joshjung if you have any additional questions please let me know.
