### ISSUE TITLE
Create a keystone 0.3x compatible version of KSL

### ISSUE THREAD

**Issue by estilles** [JohnnyEstilles/keystone-social-login#8]
This new version will include:
- a more simplified API
- update to latest passport-google-oauth strategy (issue #6)
- update to latest passport-facebook strategy (issue #5)
- use Keystone branding options to generated KSL login view
- convert KSL Login view into a react component

**Comment by ryankeener** [comment]
Really liked using this on 0.2.x, what's the estimate for having this ready for 0.3.x?

**Comment by estilles** [comment]
@ryankeener! Thank for your feedback! I'm actually looking forward to a `0.3.x` compatible version myself. I've actually been waiting for two from Keystone:
1. `0.3.x` to somewhat stabilize
2. a proposed plugin architecture, because @JedWatson once mentioned that he preferred a builtin mechanism for modules to register themselves with Keystone, rather than plugin themselves in, as the current version of KSL does at the moment with `0.2.x` (see discussion in issues [185](https://github.com/keystonejs/keystone/issues/185) and [912](https://github.com/keystonejs/keystone/issues/912) regarding plugins for Keystone).

The former is just a matter of time. The latter will require consensus among Keystone repo owners and collaborators, which doesn't appear to exist at the moment.

Should these two issue be resolved I would be happy to start work on my next version of KSL.

**Comment by JMLX42** [comment]
I'm also interested. Any progress?

**Comment by alobodig** [comment]
Has 0.3.x stabilized enough to continue with this?

**Comment by kadosh1000** [comment]
Any news?
